version: '3.2'
services:
# Influx db for timeseries metrics storage
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
        env_file:
        - 'env.influxdb'
        volumes:
        - /opt/influxdb/data:/var/lib/influxdb
# Grafana Instance for visualization / dashboards
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
        - "3000:3000"
        env_file:
        - 'env.grafana'
        user: "0"
        links:
        - influxdb
        volumes:
        - /opt/grafana/data:/var/lib/grafana
# Cadvisor+redis for Docker container monitoring
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        ports:
        - 8080:8080
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
        - redis
    redis:
        image: redis:latest
        container_name: redis_cadvisor
        ports:
        - 6379:6379