set SERVER_NAME="=7Cav=ARMA3 Development Server 2 [US]"
set STEAM_USERNAME=
set STEAM_PASSWORD=
set SCRIPTS_BASE_PATH=
set ARMA_BASE_PATH=
set STEAM_BASE_PATH=
set RCON_PASSWORD=
set RCON_PORT=
set INGAME_PASSWORD=
set INGAME_ADMIN_PASSWORD=
set CIPHER_SECRET_KEY=
