name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: 'tarkas/arma3/development/development1.json,
tarkas/arma3/development/development2.json,
tarkas/arma3/training/training1.json,
tarkas/arma3/training/training2.json,
tarkas/arma3/training/training3.json,
tarkas/arma3/training/training4.json,
tarkas/arma3/public/tacticalrealism1.json,
tarkas/arma3/public/tacticalrealism2.json,
mcgehee/squad/training/training1.json'