# https://github.com/snapcart/json-schema-validator
on: [pull_request]
name: PR Json Validator
jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON with Glob
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ${{ github.workspace }}/schema.json
          jsons: '*.json'
